version: "3.9"

services:
  app:
    hostname: "web"
    build: .
    command: python manage.py runserver 0.0.0.0:8000
    ports:
      - "8000:8000"
    env_file:
      - "./.env"
    depends_on:
      - "postgres"

  postgres:
    hostname: "postgres"
    image: "postgres:13.2"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      POSTGRES_DB: "postgres"
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"

  redis:
    hostname: "redis"
    image: "redis:7-alpine"
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data

  redis-commander:
    container_name: redis-commander
    hostname: redis-commander
    image: ghcr.io/joeferner/redis-commander:latest
    restart: always
    environment:
      - REDIS_HOSTS=local:redis:6379
    ports:
      - "8081:8081"

  celery:
    build: .
    command: celery -A geoheat.celery worker -l INFO --purge --pool=solo -Q parser
    env_file:
      - "./.env"

volumes:
  postgres_data:
  redis_data: